# Translator MetaKGs

See: https://github.com/NCATSTranslator/Translator_component_toolkit/issues/38

2026-06-01

In [1]:
from TCT import translator_metakg, translator_query, name_resolver, TCT_neighborhood_finder, TCT_pathfinder

In [2]:
APInames, metaKG, Translator_KP_info= translator_metakg.load_translator_resources(use_new_metakg_url=True)

Skipping server without x-maturity: {'url': '/sipr'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
imProving Agent for TRAPI 1.5 - no hits found in new metakg URL, trying old URL pattern
CATRAX BigGIM DrugResponse Performance Phase KP - TRAPI 1.5.0 - no hits found in new metakg URL, trying old URL pattern
CATRAX Pharmacogenomics KP - TRAPI 1.5.0 - no hits found in new metakg URL, trying old URL pattern
OpenPredict API - no hits found in new metakg URL, trying old URL pattern
mediKanren - no hits found in new metakg URL, trying old URL pattern
Knowledge Collaboratory API - no hits found in new metakg URL, trying old URL pattern
Sri-node-normalizer(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd SIPR - no hits found in new metakg URL, trying old URL pattern
Cqs(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Aragorn(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd-arax(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Answer-coalesce(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd-aragorn(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Autonomous Relay System (ARS) TRAPI - no hits found in new metakg URL, trying old URL pattern
Shepherd-bte(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
SPOKE KP for TRAPI 1.5 - no hits found in new metakg URL, trying old URL pattern
Workflow-runner(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Sri-answer-appraiser(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Aragorn(Trapi v1.6.0) - no hits found in new metakg URL, trying old URL pattern

In [17]:
metaKG.loc[metaKG['API'] =='CATRAX BigGIM DrugResponse Performance Phase KP - TRAPI 1.5.0']

,API,Predicate,Subject,Object,URL
19605,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:expressed_in,biolink:Gene,biolink:Cell,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19606,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:physically_interacts_with,biolink:Gene,biolink:Gene,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19607,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:gene_associated_with_condition,biolink:Gene,biolink:Disease,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19608,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:associated_with_sensitivity_to,biolink:Gene,biolink:SmallMolecule,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19609,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:associated_with_resistance_to,biolink:Gene,biolink:SmallMolecule,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19610,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:associated_with_resistance_to,biolink:Gene,biolink:MolecularMixture,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19611,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:associated_with_sensitivity_to,biolink:Gene,biolink:MolecularMixture,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19612,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:biomarker_for,biolink:Gene,biolink:Disease,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19613,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:physically_interacts_with,biolink:SmallMolecule,biolink:Gene,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19614,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:physically_interacts_with,biolink:MolecularMixture,biolink:Gene,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...
19615,CATRAX BigGIM DrugResponse Performance Phase K...,biolink:genetically_interacts_with,biolink:Gene,biolink:Gene,https://multiomics.rtx.ai:9990/BigGIM_DrugResp...

In [4]:
APInames_old, metaKG_old, Translator_KP_info_old = translator_metakg.load_translator_resources(use_new_metakg_url=False)

Skipping server without x-maturity: {'url': '/sipr'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}

In [15]:


# merge the two dataframes
metaKG_old.loc[metaKG_old['API'] == 'Retriever']

,API,Predicate,Subject,Object,URL
10624,Retriever,biolink:has_phenotype,biolink:Protein,biolink:PhenotypicFeature,https://retriever.ci.transltr.io/query/
10625,Retriever,biolink:has_phenotype,biolink:Gene,biolink:Disease,https://retriever.ci.transltr.io/query/
10626,Retriever,biolink:has_phenotype,biolink:Protein,biolink:Disease,https://retriever.ci.transltr.io/query/
10627,Retriever,biolink:has_substrate,biolink:SmallMolecule,biolink:Gene,https://retriever.ci.transltr.io/query/
10628,Retriever,biolink:has_substrate,biolink:Drug,biolink:Protein,https://retriever.ci.transltr.io/query/
...,...,...,...,...,...
14948,Retriever,biolink:affects,biolink:SmallMolecule,biolink:Gene,https://retriever.ci.transltr.io/query/
14949,Retriever,biolink:coexists_with,biolink:Gene,biolink:SmallMolecule,https://retriever.ci.transltr.io/query/
14950,Retriever,biolink:affects,biolink:Gene,biolink:SmallMolecule,https://retriever.ci.transltr.io/query/
14951,Retriever,biolink:interacts_with,biolink:Gene,biolink:SmallMolecule,https://retriever.ci.transltr.io/query/
14952,Retriever,biolink:correlated_with,biolink:SmallMolecule,biolink:SmallMolecule,https://retriever.ci.transltr.io/query/